### ISSUE TITLE
Error on calling box.info function

### ISSUE THREAD

**Issue by ParshinPavel** [viciious/go-tarantool#41]
Hi,

I'm trying to get the information about an instance calling a function `box.info` or returning 'box.info.replication'. As a result I got the error like that: "Error decoding packet type 0: msgp: attempted to decode type "int" with method for "str""

I suppose that library doesn't expect a number in map key, e.g.:

```
  replication:
    1:
      id: 1
      uuid: 294e7310-13f0-4690-b136-169599e87ba0
      lsn: 1203755966
    2:
      id: 2
      uuid: 62f23532-0291-42bf-b133-2c9db163aef6
      lsn: 0
      upstream:
        peer: user@replication:14301
        lag: 0.00088262557983398
        status: disconnected
        idle: 2119854.3704827
      downstream:
        status: stopped
        message: writev(2), called on fd 24
```

I wonder if there any workaround for such problem?
